name: playground

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      dispatch_source_repository:
        description: 'dispatch source repo'
      dispatch_run_id:
        description: 'run id for the dispatch source'

jobs:
  playground:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: curl is available?
        run: curl httpbin.org/ip
      - name: runs shell script?
        run: chmod +x ./workflow_dispatch.sh && ./workflow_dispatch.sh
      - name: env vars in step name $GITHUB_REPOSITORY
        run: echo $GITHUB_REPOSITORY
      - name: env vars in step name ${{ github.ref }}
        env:
          GITHUB_REF: ${{ github.ref}}
        run: echo $GITHUB_REF
      - name: env vars in step name ${{ GITHUB_ACTOR }}
        run: echo $GITHUB_ACTOR
      - name: Dump github context
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
