name: playground-foo

on:
  pull_request:
    branches: ["**"]

jobs:
  playground:
    env:
      DESTINATION_PATH: ${{github.event.repository.name}}/${{ github.event.pull_request.head.ref }}/${{github.run_number}}.zip
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: env vars in step name $GITHUB_REPOSITORY
      run: echo $GITHUB_REPOSITORY

    - name: env vars in step name ${{ github.ref }}
      env:
        GITHUB_REF_NEW: ${{ github.ref}}
      run: echo $GITHUB_REF_NEW

    - name: Branch name
      run: echo $GITHUB_REF

    - name: Repo name
      run: echo ${{github.event.repository.name}}

    - name: Github action number
      run: echo ${{github.run_number}}

    - name: Branch name in raw form
      run: echo ${ ${{ github.event.pull_request.head.ref }} | sed -r 's#/+#-#g'}

    - name: Build action artifacts folder name
      run: echo $DESTINATION_PATH