name: playground-foo

on:
  push:
    branches:
    - master

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Build Destination path
      run: |
        BRANCH_NAME=$(echo ${{ github.ref_name }} | sed -r 's#/+#-#g')
        echo "DESTINATION_PATH=${{github.event.repository.name}}/${BRANCH_NAME}/${{github.run_number}}" >> $GITHUB_ENV

    - name: env vars in step name $GITHUB_REPOSITORY
      run: echo $GITHUB_REPOSITORY

    - name: env vars in step name ${{ github.ref }}
      env:
        GITHUB_REF: ${{ github.ref}}
      run: echo $GITHUB_REF

    - name: Branch name
      run: echo ${GITHUB_REF##*/}

    - name: Repo name
      run: echo ${{github.event.repository.name}}

    - name: Github action number
      run: echo ${{github.run_number}}

    - name: Branch name in raw form
      run: echo ${{ github.ref_name }}

    - name: Build action artifacts folder name
      run: echo $DESTINATION_PATH