name: playground-foo

on:
  pull_request:
    branches: ["**"]

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Build Destination path
      run: |
        BRANCH_REF_NAME=$(echo ${{ github.event.pull_request.head.ref }} | sed -r 's#/+#-#g')
        echo "BRANCH_NAME=${BRANCH_REF_NAME}" >> $GITHUB_ENV
        echo "DESTINATION_PATH=${{github.event.repository.name}}/${BRANCH_REF_NAME}/${{github.run_number}}" >> $GITHUB_ENV

    - name: env vars in step name $GITHUB_REPOSITORY
      run: echo $GITHUB_REPOSITORY

    - name: bracnh name on PR in step name ${{ github.ref }}
      run: echo ${{ github.ref}}

    - name: Branch name
      run: echo ${GITHUB_REF##*/}

    - name: Repo name
      run: echo ${{github.event.repository.name}}

    - name: Github action number
      run: echo ${{github.run_number}}

    - name: Branch name in raw form
      run: echo ${{ github.ref_name }}

    - name: Build action artifacts folder name
      run: echo $DESTINATION_PATH

    - name: Check pull request name
      run: echo ${{ github.event.pull_request.head.ref }}

    - name: Teemp check
      if: ${{ env.BRANCH_NAME == 'try-and-test' }}
      run: echo Success

    - name: Temp check
      if: ${{ env.BRANCH_NAME }} == 'try-and-test'
      run: echo Success

    - name: Echo branch name
      run: echo $BRANCH_NAME

    - name: Echo branch name
      run: echo ${{ env.BRANCH_NAME }}

    - name: Set up Node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Generate API docs
      run: |
        npx redoc-cli bundle --output index.html .github/workflows/spec.yml \
        --options.theme.logo.gutter="30px" \
        --options.theme.spacing.sectionVertical=5

    - name: Upload Api Spec to Github artifacts
      uses: actions/upload-artifact@v3
      with:
        name: api-spec
        path: index.html
        retention-days: 1