name: playground-foo

on:
  pull_request:
    branches: ["**"]

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Build Destination path
      run: |
        BRANCH_NAME=$(echo ${{ github.event.pull_request.head.ref }} | sed -r 's#/+#-#g')
        echo "DESTINATION_PATH=${{github.event.repository.name}}/${BRANCH_NAME}/${{github.run_number}}" >> $GITHUB_ENV

    - name: env vars in step name $GITHUB_REPOSITORY
      run: echo $GITHUB_REPOSITORY

    - name: env vars in step name ${{ github.ref }}
      env:
        GITHUB_REF_NEW: ${{ github.ref}}
      run: echo $GITHUB_REF_NEW

    - name: Branch name
      run: echo $GITHUB_REF

    - name: Repo name
      run: echo ${{github.event.repository.name}}

    - name: Github action number
      run: echo ${{github.run_number}}

    - name: Check Destination path
      run: echo "${{ env.DESTINATION_PATH }}"

    - name: Branch name
      run: echo $BRANCH

    - name: Build Event Spec Destination path
      run: |
        echo "EVENT_SPEC_DESTINATION_PATH= medly-dev-test-cases/${{ github.event.repository.name }}/event-spec" >> $GITHUB_ENV

    - name: Build Test Coverage Destination path
      run: |
        echo "TEST_COVERAGE_DESTINATION_PATH= medly-dev-test-cases/${{ github.event.repository.name }}/test-coverage" >> $GITHUB_ENV

    - name: Check event spec dest path
      run: echo $EVENT_SPEC_DESTINATION_PATH

    - name: Check test coverage dest path
      run: echo $TEST_COVERAGE_DESTINATION_PATH